#
# 2023年2月6日 bianpeng
#


# 鼠标事件
LEFT_BUTTON_PRESS = 'LEFT_BUTTON_PRESS'
LEFT_BUTTON_RELEASE = 'LEFT_BUTTON_RELEASE'

LEFT_BUTTON_BEGIN_DRAG = 'LEFT_BUTTON_BEGIN_DRAG'
LEFT_BUTTON_DRAG = 'LEFT_BUTTON_DRAG'
LEFT_BUTTON_END_DRAG = 'LEFT_BUTTON_END_DRAG'
LEFT_BUTTON_CLICK = 'LEFT_BUTTON_CLICK'

RIGHT_BUTTON_PRESS = 'RIGHT_BUTTON_PRESS'
RIGHT_BUTTON_RELEASE = 'RIGHT_BUTTON_RELEASE'

RIGHT_BUTTON_BEGIN_DRAG = 'RIGHT_BUTTON_BEGIN_DRAG'
RIGHT_BUTTON_DRAG = 'RIGHT_BUTTON_DRAG'
RIGHT_BUTTON_END_DRAG = 'RIGHT_BUTTON_END_DRAG'
RIGHT_BUTTON_CLICK = 'RIGHT_BUTTON_CLICK'

WHEEL_UP_PRESS = 'WHEEL_UP_PRESS'
WHEEL_DOWN_PRESS = 'WHEEL_DOWN_PRESS'

KEY_PRESS = 'KEY_PRESS'

# 场景事件
SCENE_UNIT_CLICK = 'SCENE_UNIT_CLICK'
SCENE_GROUND_CLICK = 'SCENE_GROUND_CLICK'

# 开始游戏，三个事件
APP_LAUNCH = 'APP_LAUNCH'
START_GAME = 'START_GAME'
MAIN_PLAYER_READY = 'MAIN_PLAYER_READY'


# UI 面板事件
MAINUI_REFRESH = 'MAINUI_REFRESH'

NAV_PANEL_GAIN_CITY = 'NAV_PANEL_GAIN_CITY'
NAV_PANEL_LOSE_CITY = 'NAV_PANEL_LOSE_CITY'


# signal
# 这几个必须小写, 系统要求的
PRESSED = 'pressed'
GUI_INPUT = 'gui_input'
VALUE_CHANGED = 'value_changed'
TAB_CHANGED = 'tab_changed'
ITEM_SELECTED = 'item_selected'


